### ISSUE TITLE
Error when run make on windows

### ISSUE THREAD

**Issue by hossam-houssien** [odpf/columbus#14] opened 2021-06-20 12:09 UTC
trying to compile columbus with go, we got the following errors for each try/proxy conf.

>go version
go version go1.16.5 windows/amd64

> go env GOPROXY GONOPROXY
https://proxy.golang.org,direct

> cd  path\to\columbus

> make
go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
go: github.com/PaesslerAG/jsonpath@v0.1.1: Get "https://proxy.golang.org/github.com/%21paessler%21a%21g/jsonpath/@v/v0.1.1.mod": read tcp 10.20.3.143:61982->64.233.177.141:443: wsarecv: An existing connection was forcibly closed by the remote host.
make: *** [Makefile:10: build] Error 1

>  go env -w GONOPROXY=https://github.com
> go env GOPROXY GONOPROXY
https://proxy.golang.org,direct
https://github.com

>make
go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
go: github.com/PaesslerAG/jsonpath@v0.1.1: Get "https://proxy.golang.org/github.com/%21paessler%21a%21g/jsonpath/@v/v0.1.1.mod": read tcp 10.20.3.143:62019->64.233.177.141:443: wsarecv: An existing connection was forcibly closed by the remote host.
make: *** [Makefile:10: build] Error 1

>go env -w GOPROXY=direct
>go env GOPROXY GONOPROXY
direct
https://github.com

>make
go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
go: github.com/PaesslerAG/jsonpath@v0.1.1: reading github.com/PaesslerAG/jsonpath/go.mod at revision v0.1.1: unknown revision v0.1.1
make: *** [Makefile:10: build] Error 1

>go env -u GONOPROXY
>go env -w GOPROXY=http://my.company.proxy:port

>make
go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
go: github.com/PaesslerAG/jsonpath@v0.1.1: reading http://<my.comany.proxy:port>/github.com/%21paessler%21a%21g/jsonpath/@v/v0.1.1.mod: 403 Forbidden
make: *** [Makefile:10: build] Error 1

**Comment by hossam-houssien** [comment] 2021-06-20 12:28
trying again, after get rid of my company proxy 

> go env GOPROXY GONOPROXY
direct

>make
  go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
  go: github.com/elastic/go-elasticsearch@v0.0.0: reading github.com/elastic/go-elasticsearch/go.mod at revision v0.0.0: unknown revision v0.0.0
  make: *** [Makefile:10: build] Error 1

**Comment by StewartJingga** [comment] 2021-06-20 14:36
Hi  @hossam-houssien, I tried reproducing your error but no success.
> go version
> go version go1.16.5 windows/amd64

> go env GOPROXY GONOPROXY
> https://proxy.golang.org,direct

> make
> The system cannot find the path specified.
> go build -ldflags "-X main.Version=" "github.com/odpf/columbus"
> \# get https://proxy.golang.org/github.com/elastic/go-elasticsearch/@v/v0.0.0.mod
> \# get https://proxy.golang.org/github.com/hashicorp/consul/api/@v/v1.1.0.mod
> \# get https://proxy.golang.org/github.com/smartystreets/assertions/@v/v0.0.0-20180927180507-b2de0cb4f26d.mod
> \# get https://proxy.golang.org/github.com/coreos/etcd/@v/v3.3.13+incompatible.mod
> ...

which built `columbus.exe` at the end.

Can you try installing the package manually by running
`go get github.com/PaesslerAG/jsonpath@v0.1.1`

**Comment by hossam-houssien** [comment] 2021-06-20 15:19
turned out it was a bad day for our vpn system "cisco anyconnect", so I had to shutdown on my pc, and now I got columbus.exe.
thanks a lot

**Comment by StewartJingga** [comment] 2021-06-21 03:01
Oh glad to hear it is working.
Will close the issue since it seems to be resolved. 😄

**Closed by StewartJingga** 2021-06-21 03:01 UTC
